name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # allow manual run
  workflow_call:
    inputs:
      is_release:
        description: "Version type"
        required: false
        type: boolean
        default: false

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.value }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: poetry install --no-root

      - name: Set version
        id: version
        run: |
          read_version=$(poetry run sync-ver)
          if [ "${{ inputs.is_release }}" == "false" ]; then
            echo "value=${read_version}.b.${{ github.run_number }}" >> $GITHUB_OUTPUT
          else
            echo "value=${read_version}" >> $GITHUB_OUTPUT
          fi

      - name: Pack app
        run: |
          mkdir -p out
          poetry run python -m zipapp mcsi -o out/mcsi-${{ steps.version.outputs.value }}.pyz -m main:main

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: MCSI-${{ steps.version.outputs.value }}
          path: out/

  build-fat:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            os_name: linux
          - os: windows-latest
            os_name: win
    outputs:
      version: ${{ steps.version.outputs.value }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
      
      - name: Add Poetry to PATH
        run: |
          if [ "$RUNNER_OS" == "Windows" ]; then
            echo "$APPDATA\\Python\\Scripts" >> $GITHUB_PATH
          else
            echo "$HOME/.local/bin" >> $GITHUB_PATH
          fi
        shell: bash
    
      - name: Check Poetry installation
        run: poetry --version

      - name: Vendor dependencies
        shell: bash
        run: |
          poetry self add poetry-plugin-export
          poetry export --without-hashes --format=requirements.txt > requirements-poetry.txt
          mkdir -p mcsi/_vendor
          pip install -r requirements-poetry.txt --target mcsi/_vendor

      - name: Set version
        id: version
        run: |
          read_version=$(poetry run sync-ver)
          if [ "${{ inputs.is_release }}" == "false" ]; then
            echo "value=${read_version}.b.${{ github.run_number }}" >> $GITHUB_OUTPUT
          else
            echo "value=${read_version}" >> $GITHUB_OUTPUT
          fi

      - name: Build fat zipapp
        shell: bash
        run: |
          mkdir -p out
          poetry run python -m zipapp mcsi -o out/mcsi-${{ steps.version.outputs.value }}-fat-${{matrix.os_name}}.pyz -m main:main

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: MCSI-${{ steps.version.outputs.value }}-fat-${{ matrix.os_name }}
          path: out/
